# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2

phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore SM64.Net/SM64.Net.fsproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build SM64.Net/SM64.Net.fsproj

  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 --self-contained true -o deploy SM64.Net/SM64.Net.fsproj
      - ls -a
      - ls deploy

artifacts:
  files:
    - '**/*'
  base-directory: deploy
  discard-paths: no